export default {
  form: document.querySelector('.rss-form'),
  hint: document.querySelector('.agr-example'),
  posts: document.querySelector('.posts'),
  feeds: document.querySelector('.feeds'),
  input: document.getElementById('form-input'),
  header: document.querySelector('.agr-header'),
  formLabel: document.querySelector('.rss-form label'),
  formSubmit: document.querySelector('.rss-submit'),
  dataSection: document.getElementById('section-data'),
  menuSection: document.getElementById('section-menu'),
  description: document.querySelector('.agr-description'),
  notification: document.querySelector('.feedback'),
  formSubmitContainer: document.querySelector('.rss-submit .spinner-container'),
  formSubmitDescription: document.querySelector('.rss-submit .button-description'),
  modalTitle: document.querySelector('.modal-title'),
  modalBody: document.querySelector('.modal-body'),
  modalButtonRead: document.querySelector('.modal-footer a'),
  modalButtonClose: document.querySelector('.modal-footer button'),
  formSwitchLabel: document.querySelector('.form-switch-label'),
  formSwitchCheckbox: document.getElementById('changeLngButton'),
  footerText: document.querySelector('.footer-text'),
};
